### ISSUE TITLE
Support for multiple email accounts

### ISSUE THREAD

**Issue by TalAloni** [murataya/o2popper#3]
Hi,
Reviewing the code it seems there is some sort of support for multiple email accounts (e.g. [this](https://github.com/murataya/o2popper/blob/ec41ac490e6f82ad2deabdb0dda1b888dc29528b/o2pop.py#L146))
However, there seem to be [this](https://github.com/murataya/o2popper/blob/ec41ac490e6f82ad2deabdb0dda1b888dc29528b/o2pop.py#L145) logic in place to override the username detection mechanism.

I would expect that we would explicitly set the username only if it was not provided, and would appreciate if you could explain whether we can / should improve this logic to improve usability when a single o2popper instance is serving multiple users using the same client_id / secret. (we want to avoid an accidental override of the username)

Thanks!

**Comment by murataya** [comment]
I haven't documented it because of insufficient support for multiple accounts.

If you do not specify the username, it will work with multiple accounts.
However, they must have the same client_id / secret.

I'm currently working on a refurbishment to support multiple accounts.

My development is slow and you may not be able to wait. I'm sorry.

**Comment by TalAloni** [comment]
It works well for my purposes - thanks!
